[workspace]

members = [
    "gtether",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ump = "0.12"
vulkano = "0.34"
winit = { version = "0.29", features = ["x11", "rwh_05"] }

[workspace.dependencies.gtether]
path = "gtether"
