[workspace]

members = [
    "gtether",
    "examples/*",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
nalgebra-glm = { version = "0.18.0", features = ["convert-bytemuck"]}
parking_lot = "0.12"
ump = "0.12"
vulkano = "0.34"
winit = { version = "0.29", features = ["x11", "rwh_05"] }

[workspace.dependencies.gtether]
path = "gtether"
